# Generated by Django 5.0.14 on 2025-10-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_setup_2fa',
            field=models.BooleanField(default=True, help_text='Nếu True: user bị ép phải quét QR và bật OTP trước khi dùng hệ thống.'),
        ),
    ]
