# Generated by Django 5.0.14 on 2025-10-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_setup_2fa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_2fa_for_new_users', models.BooleanField(default=True, help_text='Nếu bật: tài khoản mới tạo sẽ bị ép phải setup 2FA ngay lần đầu đăng nhập.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
