# Generated by Django 5.0.14 on 2025-10-28 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_securitypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='True = user sẽ bị chuyển sang trang đổi mật khẩu trước khi vào dashboard.'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_locked',
            field=models.BooleanField(default=False, help_text='True = tạm khóa giai đoạn OTP vì nhập sai quá nhiều lần.'),
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('LOGIN_SUCCESS', 'LOGIN_SUCCESS'), ('OTP_SUCCESS', 'OTP_SUCCESS'), ('OTP_FAIL', 'OTP_FAIL'), ('OTP_LOCKED', 'OTP_LOCKED'), ('FORCED_2FA', 'FORCED_2FA'), ('RESET_OTP', 'RESET_OTP'), ('FORCE_PW_RESET', 'FORCE_PW_RESET')], max_length=32)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
