# Generated by Django 5.2.7 on 2025-10-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_failed_otp_attempts_user_must_change_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enforce_2fa', models.BooleanField(default=False, help_text='Bắt buộc tất cả tài khoản phải bật 2FA')),
                ('otp_digits', models.PositiveSmallIntegerField(default=6)),
                ('otp_period', models.PositiveSmallIntegerField(default=30)),
                ('lockout_threshold', models.PositiveSmallIntegerField(default=5, help_text='Sai OTP tối đa trước khi khoá')),
            ],
        ),
    ]
