# Generated by Django 5.2.7 on 2025-11-06 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='event',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'LOGIN_SUCCESS'), ('OTP_SUCCESS', 'OTP_SUCCESS'), ('OTP_FAIL', 'OTP_FAIL'), ('OTP_LOCKED', 'OTP_LOCKED'), ('FORCED_2FA', 'FORCED_2FA'), ('RESET_OTP', 'RESET_OTP'), ('FORCE_PW_RESET', 'FORCE_PW_RESET'), ('EMAIL_OTP_SENT', 'EMAIL_OTP_SENT'), ('BACKUP_CODE_USED', 'BACKUP_CODE_USED')], max_length=32),
        ),
        migrations.CreateModel(
            name='BackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='Mã khôi phục đã được hash', max_length=128)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
