# Generated by Django 5.2.8 on 2025-11-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_avatar_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitylog',
            name='event',
        ),
        migrations.AddField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'LOGIN_SUCCESS'), ('OTP_SUCCESS', 'OTP_SUCCESS'), ('OTP_FAIL', 'OTP_FAIL'), ('OTP_LOCKED', 'OTP_LOCKED'), ('FORCED_2FA', 'FORCED_2FA'), ('RESET_OTP', 'RESET_OTP'), ('FORCE_PW_RESET', 'FORCE_PW_RESET'), ('EMAIL_OTP_SENT', 'EMAIL_OTP_SENT'), ('BACKUP_CODE_USED', 'BACKUP_CODE_USED'), ('PASSWORD_CHANGED', 'PASSWORD_CHANGED'), ('ENABLE_2FA', 'ENABLE_2FA'), ('DISABLE_2FA', 'DISABLE_2FA')], db_column='event', max_length=32, null=True),
        ),
    ]
