# Generated by Django 5.2.8 on 2025-11-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_securitylog_event_securitylog_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylog',
            name='user_agent',
            field=models.CharField(blank=True, help_text='Thông tin thiết bị/trình duyệt', max_length=255, null=True),
        ),
    ]
