# Generated by Django 5.2.8 on 2025-12-15 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_securitylog_user_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupcode',
            options={'verbose_name': 'Mã khôi phục', 'verbose_name_plural': 'Mã khôi phục'},
        ),
        migrations.AlterModelOptions(
            name='securityconfig',
            options={'verbose_name': 'Cấu hình bảo mật', 'verbose_name_plural': 'Cấu hình bảo mật'},
        ),
        migrations.AlterModelOptions(
            name='securitylog',
            options={'verbose_name': 'Nhật ký bảo mật', 'verbose_name_plural': 'Nhật ký bảo mật'},
        ),
        migrations.AlterModelOptions(
            name='securitypolicy',
            options={'verbose_name': 'Chính sách bảo mật', 'verbose_name_plural': 'Chính sách bảo mật'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Danh sách người dùng'},
        ),
        migrations.AlterField(
            model_name='backupcode',
            name='code_hash',
            field=models.CharField(help_text='Mã khôi phục đã được hash', max_length=128, verbose_name='Mã Hash'),
        ),
        migrations.AlterField(
            model_name='backupcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='backupcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Đã sử dụng'),
        ),
        migrations.AlterField(
            model_name='backupcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='securityconfig',
            name='enforce_2fa',
            field=models.BooleanField(default=False, help_text='Bắt buộc tất cả tài khoản phải bật 2FA', verbose_name='Bắt buộc 2FA toàn hệ thống'),
        ),
        migrations.AlterField(
            model_name='securityconfig',
            name='lockout_threshold',
            field=models.PositiveSmallIntegerField(default=5, help_text='Sai OTP tối đa trước khi khoá', verbose_name='Ngưỡng khóa (lần sai)'),
        ),
        migrations.AlterField(
            model_name='securityconfig',
            name='otp_digits',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Độ dài OTP'),
        ),
        migrations.AlterField(
            model_name='securityconfig',
            name='otp_period',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Chu kỳ OTP (giây)'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'LOGIN_SUCCESS'), ('OTP_SUCCESS', 'OTP_SUCCESS'), ('OTP_FAIL', 'OTP_FAIL'), ('OTP_LOCKED', 'OTP_LOCKED'), ('FORCED_2FA', 'FORCED_2FA'), ('RESET_OTP', 'RESET_OTP'), ('FORCE_PW_RESET', 'FORCE_PW_RESET'), ('EMAIL_OTP_SENT', 'EMAIL_OTP_SENT'), ('BACKUP_CODE_USED', 'BACKUP_CODE_USED'), ('PASSWORD_CHANGED', 'PASSWORD_CHANGED'), ('ENABLE_2FA', 'ENABLE_2FA'), ('DISABLE_2FA', 'DISABLE_2FA')], db_column='event', max_length=32, null=True, verbose_name='Loại sự kiện'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='ip',
            field=models.CharField(blank=True, max_length=64, verbose_name='Địa chỉ IP'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='user_agent',
            field=models.CharField(blank=True, help_text='Thông tin thiết bị/trình duyệt', max_length=255, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='securitypolicy',
            name='require_2fa_for_new_users',
            field=models.BooleanField(default=True, help_text='Nếu bật: tài khoản mới tạo sẽ bị ép phải setup 2FA ngay lần đầu đăng nhập.', verbose_name='Yêu cầu 2FA cho người dùng mới'),
        ),
        migrations.AlterField(
            model_name='securitypolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Giới thiệu ngắn về bạn', null=True, verbose_name='Tiểu sử'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Địa chỉ Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Đã xác thực Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='failed_otp_attempts',
            field=models.IntegerField(default=0, verbose_name='Số lần nhập sai OTP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, verbose_name='Đã bật 2FA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Nếu chọn: Người dùng sẽ bị chuyển sang trang đổi mật khẩu ở lần đăng nhập tới.', verbose_name='Yêu cầu đổi mật khẩu'),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_setup_2fa',
            field=models.BooleanField(default=True, help_text='Nếu chọn: Người dùng bị ép phải quét mã QR và bật OTP trước khi dùng hệ thống.', verbose_name='Bắt buộc thiết lập 2FA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_locked',
            field=models.BooleanField(default=False, help_text='Nếu chọn: Tạm khóa tính năng nhập OTP do người dùng nhập sai quá nhiều lần.', verbose_name='Đang bị khóa OTP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Mã bí mật OTP (Secret)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('USER', 'User')], default='USER', max_length=10, verbose_name='Vai trò'),
        ),
    ]
