# Generated by Django 5.2.8 on 2025-12-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_secret',
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_otp_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã OTP (Đã mã hóa)'),
        ),
    ]
