# Generated by Django 5.2.8 on 2025-12-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_user_otp_secret_user_encrypted_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_email_otp',
            field=models.BooleanField(default=True, help_text="Nếu bỏ chọn: User chỉ được dùng App Authenticator, không được bấm nút 'Gửi qua Email'.", verbose_name='Cho phép nhận OTP qua Email'),
        ),
    ]
