# Generated by Django 5.2.8 on 2025-12-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_allow_email_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityconfig',
            name='enforce_2fa',
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='allow_email_otp_system',
            field=models.BooleanField(default=True, help_text='Nếu tắt: Không ai được dùng Email để nhận OTP, bắt buộc dùng App (Google Auth).', verbose_name='Cho phép OTP qua Email (Toàn hệ thống)'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='enforce_for_admin',
            field=models.BooleanField(default=True, help_text='Bắt buộc tài khoản có quyền Admin/Superuser phải bật 2FA', verbose_name='Bắt buộc 2FA với Admin'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='enforce_for_staff',
            field=models.BooleanField(default=False, help_text='Bắt buộc tài khoản nhân viên (Staff) phải bật 2FA', verbose_name='Bắt buộc 2FA với Staff'),
        ),
        migrations.AddField(
            model_name='securityconfig',
            name='enforce_for_user',
            field=models.BooleanField(default=False, help_text='Bắt buộc người dùng thường phải bật 2FA', verbose_name='Bắt buộc 2FA với User'),
        ),
    ]
