# Generated by Django 5.2.8 on 2025-12-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_securityconfig_enforce_2fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityconfig',
            name='otp_digits',
            field=models.PositiveSmallIntegerField(choices=[(6, '6 chữ số (Tiêu chuẩn)'), (8, '8 chữ số (Bảo mật cao)')], default=6, verbose_name='Độ dài OTP'),
        ),
    ]
